name: Deploy to Production Server

on:
    push:
        branches:
            - main

jobs:
    deploy:
        name: Deploy App
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Install and Build
              run: |
                  npm install
                  npm run build

            - name: Deploy to Server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.DEPLOY_SSH_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  script: |

                      set -x

                      # Navigate to the app directory
                      cd danmccollum.com

                      # Create a backup directory with the current date and time
                      backup_date=$(date +'%Y%m%d')
                      backup_time=$(date +'%H%M%S')
                      mkdir -p backup/$backup_date/$backup_time

                      # Move the existing files to the backup directory
                      [ -f index.js ] && mv index.js backup/$backup_date/$backup_time/
                      [ -d build/ ] && mv build/ backup/$backup_date/$backup_time/
                      [ -d models/ ] && mv models/ backup/$backup_date/$backup_time/

            - name: Copy Files to Server
              uses: appleboy/scp-action@master
              with:
                  host: ${{ secrets.SERVER_HOST }}
                  port: ${{ secrets.SERVER_PORT }}
                  username: ${{ secrets.SERVER_USER }}
                  key: ${{ secrets.DEPLOY_SSH_KEY }}
                  passphrase: ${{ secrets.SSH_PASSPHRASE }}
                  source: "index.js,build/,models/"
                  target: "danmccollum.com/"
